gantt
    title Exemplo de Cronograma
    dateFormat YYYY-MM-DD
    section Fase 1
    Kickoff :a1, 2026-01-06, 3d
    Planejamento :a2, after a1, 10d
    section Fase 2
    Execução :a3, after a2, 20d
    Encerramento :a4, after a3, 5d
